USE [master]
GO

/****** Object:  Database [GooberSvc]    Script Date: 5/14/2018 11:58:36 AM ******/
CREATE DATABASE [GooberSvc]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'GooberSvc', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\GooberSvc.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'GooberSvc_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\GooberSvc_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [GooberSvc] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [GooberSvc].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [GooberSvc] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [GooberSvc] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [GooberSvc] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [GooberSvc] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [GooberSvc] SET ARITHABORT OFF 
GO

ALTER DATABASE [GooberSvc] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [GooberSvc] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [GooberSvc] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [GooberSvc] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [GooberSvc] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [GooberSvc] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [GooberSvc] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [GooberSvc] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [GooberSvc] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [GooberSvc] SET  DISABLE_BROKER 
GO

ALTER DATABASE [GooberSvc] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [GooberSvc] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [GooberSvc] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [GooberSvc] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [GooberSvc] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [GooberSvc] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [GooberSvc] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [GooberSvc] SET RECOVERY FULL 
GO

ALTER DATABASE [GooberSvc] SET  MULTI_USER 
GO

ALTER DATABASE [GooberSvc] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [GooberSvc] SET DB_CHAINING OFF 
GO

ALTER DATABASE [GooberSvc] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [GooberSvc] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [GooberSvc] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [GooberSvc] SET QUERY_STORE = OFF
GO

USE [GooberSvc]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [GooberSvc] SET  READ_WRITE 
GO


